version: "3"
services:
  wordpress:
    image: wordpress
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: wordpress
      XDEBUG_CONFIG: remote_host=10.0.1.19
    volumes:
      - ../jetpack:/var/www/html/wp-content/plugins/jetpack
      - ../wordpress-develop:/tmp/wordpress-develop
      - ../errors:/var/www/html/wp-content/plugins/errors
      - ./:/var/www/html/wp-content/plugins/jurassic.ninja
      - ../jurassic.ninja-ext:/var/www/html/wp-content/plugins/jurassic.ninja-ext
      - ../jetpack-beta:/var/www/html/wp-content/plugins/jetpack-beta-master
    links:
    - wordpressdb
    - wordpressdb:mysql
    
  wordpressdb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
    volumes:
    - ./jndb:/var/lib/mysql
